name = "GaussQuadrature"
uuid = "d54b0c1a-921d-58e0-8e36-89d8069c0969"
author = ["William McLean <w.mclean@unsw.edu.au>"]
version = "0.5.6"

[deps]
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"

[compat]
SpecialFunctions = "0.8, 0.9, 0.10, 1.0"
julia = "1.2.0"

[extras]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["LinearAlgebra", "Test", "SpecialFunctions", "Printf"]
